// Sample content for the Sipp kiosk demo — Summerhill Pyramid Winery, Kelowna BC.
// Plausible mock lineup. Imagery uses labelled drop-zone placeholders.

window.WINERY = {
  name: "Summerhill Pyramid Winery",
  mark: "SP",
  region: "East Kelowna Bench · Okanagan Valley",
  tagline: "Canada's most-visited organic winery, perched above Okanagan Lake.",
  blurb: "Certified organic & biodynamic since 1989. Our sparkling wines age in a replica of the Great Pyramid.",
};

// Wineries surfaced as "where to go next" on the handoff.
window.NEXT_WINERIES = [
  { name: "CedarCreek Estate", note: "Pinot Noir flight · 12 min away", mark: "CC" },
  { name: "Quails' Gate", note: "Lakeview patio · 18 min away", mark: "QG" },
];

window.WINES = [
  {
    id: "cipes-brut",
    name: "Cipes Brut",
    grape: "Traditional Method Sparkling",
    vintage: "NV",
    type: "Sparkling",
    color: "#E9C96B",
    region: "Estate Vineyard · East Kelowna",
    notes: ["Green apple", "Brioche", "Citrus zest", "Fine mousse"],
    winemaker: "Pyramid-aged on the lees for five years. Our founding wine — the bottle that put organic Okanagan bubbles on the map.",
    pairing: "Oysters, soft brie, fresh popcorn",
    pairingIcon: "🦪",
    price: 42,
    award: "Lieutenant Governor's Award",
    placeholder: "SPARKLING BOTTLE",
  },
  {
    id: "pinot-gris",
    name: "Organic Pinot Gris",
    grape: "Pinot Gris",
    vintage: "2023",
    type: "White",
    color: "#EAD9A0",
    region: "Sustainable Block 4 · Lakeview",
    notes: ["Bartlett pear", "White peach", "Wet stone", "Crisp"],
    winemaker: "Whole-cluster pressed at dawn when the fruit is coolest. A summer-on-the-dock white with a mineral spine.",
    pairing: "Grilled prawns, goat cheese, summer salad",
    pairingIcon: "🦐",
    price: 26,
    award: null,
    placeholder: "WHITE WINE BOTTLE",
  },
  {
    id: "riesling",
    name: "Estate Riesling",
    grape: "Riesling",
    vintage: "2022",
    type: "White",
    color: "#E4D27A",
    region: "Upper Bench · East Kelowna",
    notes: ["Lime blossom", "Honeycomb", "Granny Smith", "Off-dry"],
    winemaker: "Picked across three passes for tension and lift. Ages beautifully — but it rarely lasts that long.",
    pairing: "Thai green curry, fresh chèvre",
    pairingIcon: "🍜",
    price: 24,
    award: "Gold · National Wine Awards",
    placeholder: "WHITE WINE BOTTLE",
  },
  {
    id: "rose",
    name: "Cipes Rosé",
    grape: "Pinot Noir Rosé",
    vintage: "2023",
    type: "Rosé",
    color: "#E7A9A0",
    region: "Estate Vineyard · East Kelowna",
    notes: ["Wild strawberry", "Watermelon", "Rose petal", "Dry finish"],
    winemaker: "Saignée from our Pinot Noir, kept pale and bone-dry. The colour of an Okanagan sunset over the lake.",
    pairing: "Charcuterie, grilled salmon, patio afternoons",
    pairingIcon: "🧀",
    price: 28,
    award: null,
    placeholder: "ROSÉ BOTTLE",
  },
  {
    id: "pinot-noir",
    name: "Reserve Pinot Noir",
    grape: "Pinot Noir",
    vintage: "2021",
    type: "Red",
    color: "#9C3B40",
    region: "Biodynamic Block 7 · Lakeview",
    notes: ["Dark cherry", "Forest floor", "Vanilla", "Silky finish"],
    winemaker: "From our oldest biodynamic block, fermented with native yeast and a gentle hand. Elegant, perfumed, unmistakably Okanagan.",
    pairing: "Grilled lamb, aged gouda, mushroom risotto",
    pairingIcon: "🥩",
    price: 48,
    award: "Platinum · Decanter",
    placeholder: "RED WINE BOTTLE",
  },
  {
    id: "meritage",
    name: "Pyramid Meritage",
    grape: "Cabernet · Merlot · Cab Franc",
    vintage: "2020",
    type: "Red",
    color: "#6E2630",
    region: "South-facing Bench · Estate",
    notes: ["Blackcurrant", "Cedar", "Dark chocolate", "Firm tannin"],
    winemaker: "Our flagship Bordeaux blend, aged 22 months in French oak. Built for the cellar and the long dinner.",
    pairing: "Ribeye, braised short rib, dark chocolate",
    pairingIcon: "🍫",
    price: 55,
    award: null,
    placeholder: "RED WINE BOTTLE",
  },
];
